config/routes.rb
Rails.application.routes.draw do
  get 'countries/index'
  get 'courses/index'
  get 'greeter/hello'
  get 'greeter/goodbye'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/country.rb
class Country
    include HTTParty

    default_options.update(verify: false)
    base_uri 'https://restcountries.eu/rest/v2'
    format :json

    def self.all 
        countries = get("/all")

        # Replace 'borders' country codes with actual country names
        countries.each do |country|
            country['borders'].map! do |country_code|
                countries.find { |country| country['alpha3Code'] == country_code } ['name']
            end
            country['languages'].map! { |language| language['name'] }
        end

        countries
    end
end

app/models/coursera.rb
class Coursera
    include HTTParty

    base_uri 'https://api.coursera.org/api/catalog.v1/courses'
    default_params fields: "smallIcon,shortDescription", q: "search"
    format :json

    def self.for term
        get("", query: { query: term })["elements"]
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  def index
    all_countries = Country.all
    
    # If limit is passed in - do nothing
    # Otherwise, generate a random number between 5 and 25

    limit = params[:limit].to_i
    limit = rand(5..25) if limit.zero?

    @countries_to_display = all_countries.sample(limit)
    @countries_to_display.sort! { |a, b|  a["name"] <=> b["name"] }
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @search_term = 'python'
    @courses = Coursera.for(@search_term);
  end
end

app/controllers/greeter_controller.rb
class GreeterController < ApplicationController
  def hello
    random_name = ["Alex", "Joe", "Michael"]
    @name = random_name.sample
    @time = Time.now
    @times_displayed ||= 0
    @times_displayed += 1
  end
  def goodbye
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/greeter_helper.rb
module GreeterHelper
    def formatted_time(time)
        # time string in AM/PM format
        time.strftime("%I:%M %p")
    end
end

app/views/countries/index.html.erb
<h1>Countries (<%= @countries_to_display.size %>)</h1>

<table border="1">
  <tr>
    <th>Flag</th>
    <th>Name</th>
    <th>Capital</th>
    <th>Population</th>
    <th>Languages Spoken</th>
    <th>Borders With</th>
    <th>Lat/Long</th>
  </tr>
  <% @countries_to_display.each do |country| %>
    <tr class=<%= cycle('even', 'odd') %>>
      <td><%= image_tag country["flag"], alt: "Flag of #{country['name']}", size: "100x50", class: "flag" %></td>
      <td><%= country["name"] %></td>
      <td><%= country["capital"] %></td>
      <td><%= number_to_human country["population"].to_i %></td>
      <td><%= country["languages"].join(", ") %></td>
      <td><%= country["borders"].join(", ") %></td>
      <td><%= country["latlng"].join(", ") %></td>
    </tr>
  <% end %>
</table>

app/views/courses/index.html.erb
<h1>Searching for - <%= @search_term %></h1>

<table border="1">
    <tr>
        <th>Image</th>
        <th>Name</th>
        <th>Description</th>
    </tr>
    <% @courses.each do |course| %>
        <tr>
            <td><%= image_tag(course["smallIcon"]) %></td>
            <td><%= image_tag(course["name"]) %></td>
            <td><%= image_tag(course["shortDescription"]) %></td>
        </tr>
    <% end %>
</table>

app/views/greeter/goodbye.html.erb
<h1>Goodye</h1>

app/views/greeter/hello.html.erb
<h1>Greetings, <%= @name %></h1>
<p>The time now is <%= formatted_time(@time) %></p>
<p>This page has been vieweb <%= @times_displayed %> time(s)</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyRubyApp1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
      <li><%= link_to "Hello", greeter_hello_path %></li>
      <li><%= link_to "Goodbye", greeter_goodbye_path %></li>
      <li><%= link_to "Countries", countries_index_path %></li>
    </nav>
    <%= yield %>
  </body>
</html>